package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import java.io.IOException;
import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField tfWalletName;
	@FXML
	private TextField tfWalletDescription;

	// Event Listener on Button[#closeButton].onAction
	@FXML
	public void exitBtn(ActionEvent event) {
		// TODO Autogenerated
		((Stage) (((Button) event.getSource()).getScene().getWindow())).close();
	}

	public void switchToMainScene(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("MainScene.fxml"));
		stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}

	public void switchToAddWalletScene(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("AddWalletScene.fxml"));
		stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}

	public void addWalletBtn(ActionEvent event) throws IOException {
		String walletName = tfWalletName.getText();
		String walletDesc = tfWalletDescription.getText();
		System.out.println(walletName);
		System.out.println(walletDesc);
		Parent root = FXMLLoader.load(getClass().getResource("MainScene.fxml"));
		stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
